[profiles]
mothership = [
	"git",
	"hypr",
	"kitty",
	"mako",
	"neovim",
	"nushell",
	"profile",
	"scripts",
	"swayidle",
	"waybar",
  "tmux",
]

battleship = [
	"git",
	"neovim",
	"nushell",
	"profile",
	"scripts",
  "tmux",
]

[links.git]
from = "git"
to = "$HOME/.config/git"

[links.hypr]
from = "hypr"
to = "$HOME/.config/hypr/"

[links.kitty]
from = "kitty"
to = "$HOME/.config/kitty"

[links.mako]
from = "mako"
to = "$HOME/.config/mako"

[links.nushell]
from = "nushell"
to = "$HOME/.config/nushell"

[links.neovim]
from = "nvim"
to = "$HOME/.config/nvim/lua/custom"

[links.qutebrowser]
from = "qutebrowser"
to = "$HOME/.config/qutebrowser/"

[links.waybar]
from = "waybar"
to = "$HOME/.config/waybar/"

[links.profile]
from = "dot_profile"
to = "$HOME/.profile"

[links.scripts]
from = "scripts"
to = "$HOME/.local/bin"

[links."user-dirs.dirs"]
from = "user-dirs.dirs"
to = "$HOME/.config/user-dirs.dirs"

[links.swayidle]
from = "swayidle"
to = "$HOME/.config/swayidle"

[links.tmux]
from = "tmux"
to = "$HOME/.config/tmux"

[links.zellij]
from = "zellij"
to = "/home/ama/.config/zellij/"

[links.helix]
from = "helix"
to = "$HOME/.config/helix/"
