[profiles]
mothership = [
	"neovim",
	"hypr",
	"kitty",
	"mako",
	"nushell",
	"waybar",
	"profile",
	"scripts",
	"git",
]

[links.git]
from = "git"
to = "$HOME/.config/git"

[links.hypr]
from = "hypr"
to = "$HOME/.config/hypr/"

[links.kitty]
from = "kitty"
to = "$HOME/.config/kitty"

[links.mako]
from = "mako"
to = "$HOME/.config/mako"

[links.nushell]
from = "nushell"
to = "$HOME/.config/nushell"

[links.neovim]
from = "nvim"
to = "$HOME/.config/nvim/"

[links.qutebrowser]
from = "qutebrowser"
to = "$HOME/.config/qutebrowser/"

[links.waybar]
from = "waybar"
to = "$HOME/.config/waybar/"

[links.profile]
from = "dot_profile"
to = "$HOME/.profile"

[links.scripts]
from = "scripts"
to = "$HOME/.local/bin"

[links."user-dirs.dirs"]
source = "user-dirs.dirs"
target = "$HOME/.config/user-dirs.dirs"
