theme = "catppuccin_mocha"

[editor]
line-number = "relative"
shell = ["nu", "-c"]
bufferline = "multiple"
 
[editor.lsp]
display-inlay-hints = true

[keys.normal]
"tab" = "goto_next_buffer"
"S-tab" = "goto_previous_buffer"

[keys.normal.space]
x = ":buffer-close"
