# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot = {
    initrd.availableKernelModules =
      [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
    initrd.kernelModules = [ ];
    kernelModules = [ "kvm-amd" ];
    kernelParams = [ "mitigations=off" ];
    extraModulePackages = [ ];

    kernel.sysctl."net.ipv4.icmp_ignore_broadcasts" = 1;
  };

  modules.hardware = {
    audio.enable = true;
    ergodox.enable = true;
    nvidia.enable = true;
  };

  nix.maxJobs = lib.mkDefault 12;
  powerManagement.cpuFreqGovernor = "performance";
  hardware.cpu.amd.updateMicrocode = true;

  hardware.pulseaudio.daemon.config = {
    default-sample-channels = 6;
    enable-lfe-remixing = "yes";
  };

  hardware.pulseaudio.extraConfig = ''
    set-default-sink alsa_output.pci-0000_28_00.4.analog-surround-51
  '';

  services.xserver = {
    monitorSection = ''
      VendorName     "Unknown"
      ModelName      "Samsung C49RG9x"
      HorizSync       30.0 - 190.0
      VertRefresh     50.0 - 120.0
      Option         "DPMS"
    '';

    screenSection = ''
      Option         "metamodes" "DP-2: nvidia-auto-select +0+1080, DP-4: nvidia-auto-select +0+0"
      Option         "SLI" "Off"
      Option         "MultiGPU" "Off"
      Option         "BaseMosaic" "off"
      Option         "Stereo" "0"
      Option         "nvidiaXineramaInfoOrder" "DFP-3"
    '';
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/14f7c264-2c82-49ed-b27a-b08a420d605a";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/5672-7EFF";
    fsType = "vfat";
  };

  fileSystems."/home/amatrelan/Org" = {
    device = "//192.168.100.11/amatrelan/Org";
    fsType = "cifs";
    options = let
      automount_opts = "x-systemd.automount,noauto,x-systemd.idle-timeout=60,x-systemd.device-timeout=5s,x-systemd.mount-timeout=5s";

    in ["${automount_opts},credentials=/etc/nixos/smb-secrets" "uid=amatrelan" "gid=users" "workgroup=WORKGROUP"];
  };

  fileSystems."/home/amatrelan/Projects.bak" = {
    device = "//192.168.100.11/amatrelan/Projects";
    fsType = "cifs";
    options = let
      automount_opts = "x-systemd.automount,noauto,x-systemd.idle-timeout=60,x-systemd.device-timeout=5s,x-systemd.mount-timeout=5s";

    in ["${automount_opts},credentials=/etc/nixos/smb-secrets" "uid=amatrelan" "gid=users" "workgroup=WORKGROUP"];
  };

  fileSystems."/home/amatrelan/Photos" = {
    device = "//192.168.100.11/amatrelan/Photos";
    fsType = "cifs";
    options = let
      automount_opts = "x-systemd.automount,noauto,x-systemd.idle-timeout=60,x-systemd.device-timeout=5s,x-systemd.mount-timeout=5s";

    in ["${automount_opts},credentials=/etc/nixos/smb-secrets" "uid=amatrelan" "gid=users" "workgroup=WORKGROUP"];
  };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/33c6b470-3c79-4706-9192-257a157d8e2d"; }];

}
